### ISSUE TITLE
during server migration, Neatline Exhibit files blocked due to a bug

### ISSUE THREAD

**Issue by Paul-Curtis** [scholarslab/Neatline#508]
During a recent server migration, I lost three Neatline Exhibits. Advice from the Omeka forum directed me to reveal error reporting, and then to report the error to you for help. 

On the Neatline home page (byrononlineproject.com Omeka 3.1), this warning appears: Warning: Declaration of NeatlineExhibit::beforeSave() should be compatible with Omeka_Record_AbstractRecord::beforeSave($args) in /home/byrononl/public_html/plugins/Neatline/models/NeatlineExhibit.php on line 10

Upon clicking  the first exhibit, this appears: 

Zend_Db_Statement_Mysqli_Exception: Mysqli prepare error: FUNCTION byrononl_omek1.AsText does not exist in /home/byrononl/public_html/application/libraries/Zend/Db/Statement/Mysqli.php:77
Stack trace:
#0 /home/byrononl/public_html/application/libraries/Zend/Db/Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('SELECT `neatlin...')
#1 /home/byrononl/public_html/application/libraries/Zend/Db/Adapter/Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'SELECT `neatlin...')
#2 /home/byrononl/public_html/application/libraries/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('SELECT `neatlin...')
#3 /home/byrononl/public_html/application/libraries/Zend/Db/Select.php(711): Zend_Db_Adapter_Abstract->query('SELECT `neatlin...')
#4 /home/byrononl/public_html/plugins/Neatline/models/NeatlineRecordTable.php(76): Zend_Db_Select->query()
#5 /home/byrononl/public_html/plugins/NeatlineText/NeatlineTextPlugin.php(91): NeatlineRecordTable->queryRecords(Array)
#6 /home/byrononl/public_html/application/libraries/Omeka/Plugin/Broker.php(266): NeatlineTextPlugin->filterNeatlineGlobals(Array, Array)
#7 /home/byrononl/public_html/application/libraries/globals.php(324): Omeka_Plugin_Broker->applyFilters('neatline_global...', Array, Array)
#8 /home/byrononl/public_html/plugins/Neatline/helpers/Plugins.php(89): apply_filters('neatline_global...', Array, Array)
#9 /home/byrononl/public_html/plugins/Neatline/views/shared/exhibits/partials/exhibit.php(19): nl_getGlobals(Object(NeatlineExhibit))
#10 /home/byrononl/public_html/application/libraries/Omeka/View.php(114): include('/home/byrononl/...')
#11 /home/byrononl/public_html/application/libraries/Zend/View/Abstract.php(889): Omeka_View->_run('/home/byrononl/...')
#12 /home/byrononl/public_html/application/libraries/Zend/View/Helper/Partial.php(109): Zend_View_Abstract->render(NULL)
#13 /home/byrononl/public_html/application/libraries/Zend/View/Abstract.php(350): Zend_View_Helper_Partial->partial('exhibits/partia...')
#14 /home/byrononl/public_html/plugins/Neatline/helpers/Views.php(130): Zend_View_Abstract->__call('partial', Array)
#15 /home/byrononl/public_html/plugins/Neatline/views/public/exhibits/show.php(26): nl_getExhibitMarkup()
#16 /home/byrononl/public_html/application/libraries/Omeka/View.php(114): include('/home/byrononl/...')
#17 /home/byrononl/public_html/application/libraries/Zend/View/Abstract.php(889): Omeka_View->_run('/home/byrononl/...')
#18 /home/byrononl/public_html/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(912): Zend_View_Abstract->render(NULL)
#19 /home/byrononl/public_html/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(933): Zend_Controller_Action_Helper_ViewRenderer->renderScript('exhibits/show.p...', NULL)
#20 /home/byrononl/public_html/application/libraries/Zend/Controller/Action.php(212): Zend_Controller_Action_Helper_ViewRenderer->render('show', NULL, false)
#21 /home/byrononl/public_html/plugins/Neatline/controllers/ExhibitsController.php(214): Zend_Controller_Action->render('show')
#22 /home/byrononl/public_html/application/libraries/Zend/Controller/Action.php(516): Neatline_ExhibitsController->showAction()
#23 /home/byrononl/public_html/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('showAction')
#24 /home/byrononl/public_html/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#25 /home/byrononl/public_html/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(106): Zend_Controller_Front->dispatch()
#26 /home/byrononl/public_html/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#27 /home/byrononl/public_html/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#28 /home/byrononl/public_html/index.php(23): Omeka_Application->run()
#29 {main}

This is my first request for help. Thanks in advance, and Be well ...Paul

**Comment by zerocrates** [comment]
What version of the Neatline plugin are you using? My recollection is that the last release, 2.6.4, had a fix for this problem.

**Comment by Paul-Curtis** [comment]
Dear John:

Thank you for your message. The Neatline that I have – according to system information -- is 2.4.2. I have four other Neatline plugins on the site, and each has an inferior version.

What may you suggest that I do.

Thanks, and

Be well ...Paul
________________________________

**Comment by zerocrates** [comment]
I think you'll have to upgrade Neatline to get past this problem: it's an incompatibility between your older version of Neatline and the newer database server you're now using. You'd probably want to upgrade all your Neatline plugins, I would imagine, but that might not be necessary.

Take a backup of your site and try doing the upgrade.

**Comment by Paul-Curtis** [comment]
Thank you once again, John. I have downloaded all of the upgrades and have consulted (several times) the Omeka Classic User Manual regarding updating plugins. I will also update the Omeka version. I have a backup of the data made before the migration – thanks to the folks at Reclaim Hosting. Of course, my worry is how the site will appear after the upgrades – if I've lost data or performance.

Monday is the big day for the upgrades and testing.

Be well ...Paul
________________________________
