### ISSUE TITLE
Neatline broken on my Omeka installation

### ISSUE THREAD

**Issue by wtrettien** [scholarslab/Neatline#510]
Hi! I have used Neatline to build a number of exhibits of cut-up fragments of books, in fact whole editions of books -- but the plugin is suddenly broken on my installation of Omeka. I use Reclaim Hosting, and they've looked into the issue extensively, updating my Omeka, migrating servers, updating Neatline (which is 2.6.4) -- to no avail. (I can share more about what they did if that's helpful.) 

I appreciate any thoughts or help with this!

This is the website:
https://digitalbookhistory.com/littlegidding/ 

Here is the error message I am getting when I try to load a Neatline exhibit:

Zend_Db_Statement_Mysqli_Exception
Mysqli prepare error: Table 'digita47_om2.om_neatline_simile_exhibit_expansions' doesn't exist

Zend_Db_Statement_Mysqli_Exception: Mysqli prepare error: Table 'digita47_om2.om_neatline_simile_exhibit_expansions' doesn't exist in /home/digita47/public_html/littlegidding/application/libraries/Zend/Db/Statement/Mysqli.php:77
Stack trace:
#0 /home/digita47/public_html/littlegidding/application/libraries/Zend/Db/Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('SELECT `neatlin...')
#1 /home/digita47/public_html/littlegidding/application/libraries/Zend/Db/Adapter/Mysqli.php(388): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'SELECT `neatlin...')
#2 /home/digita47/public_html/littlegidding/application/libraries/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Adapter_Mysqli->prepare('SELECT `neatlin...')
#3 /home/digita47/public_html/littlegidding/application/libraries/Zend/Db/Adapter/Abstract.php(756): Zend_Db_Adapter_Abstract->query('SELECT `neatlin...', Array)
#4 /home/digita47/public_html/littlegidding/application/libraries/Omeka/Db.php(80): Zend_Db_Adapter_Abstract->fetchRow(Object(Omeka_Db_Select), Array)
#5 /home/digita47/public_html/littlegidding/application/libraries/Omeka/Db/Table.php(669): Omeka_Db->__call('fetchRow', Array)
#6 /home/digita47/public_html/littlegidding/application/libraries/Omeka/Db/Table.php(429): Omeka_Db_Table->fetchObject(Object(Omeka_Db_Select), Array)
#7 /home/digita47/public_html/littlegidding/plugins/Neatline/models/NeatlineExhibitTable.php(56): Omeka_Db_Table->findBySql('slug=?', Array, true)
#8 /home/digita47/public_html/littlegidding/plugins/Neatline/controllers/ExhibitsController.php(202): NeatlineExhibitTable->findBySlug('gospel-harmony-...')
#9 /home/digita47/public_html/littlegidding/application/libraries/Zend/Controller/Action.php(516): Neatline_ExhibitsController->showAction()
#10 /home/digita47/public_html/littlegidding/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('showAction')
#11 /home/digita47/public_html/littlegidding/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /home/digita47/public_html/littlegidding/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(106): Zend_Controller_Front->dispatch()
#13 /home/digita47/public_html/littlegidding/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#14 /home/digita47/public_html/littlegidding/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#15 /home/digita47/public_html/littlegidding/index.php(23): Omeka_Application->run()
#16 {main}

**Comment by jamiefolsom** [comment]
Hi @wtrettien -- great to hear from you! As you may know, Performant Software's github organization is the new home of the Neatline repositories and project website and documentation. We have not yet been able to invest new resources in upkeep or development on Neatline since we took those resources over from Scholars' Lab, but we are actively exploring how to offer a path forward to existing Neatline projects.

We're not ready to announce anything specific, but I would like to help you with this if possible -- I will reach out via email to discuss further.
